os:
  - linux

cache:
  directories:
    - elm-stuff/build-artifacts
    - elm-stuff/packages

env:
  matrix:
    - ELM_VERSION=0.18.0 TARGET_NODE_VERSION=node


install:
  - nvm install $TARGET_NODE_VERSION
  - nvm use $TARGET_NODE_VERSION
  - node --version
  - npm --version
  - npm install -g elm@$ELM_VERSION elm-test elm-verify-examples
  - elm package install --yes

script:
  - elm make
  - elm-verify-examples && elm test
